version: "3.7"
services:
    themindgame-node:
        container_name: themindgame-node
        restart: unless-stopped
        environment:
            - NODE_ENV=development
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
            - "8000:8000"
            - "3000:3000"
        depends_on:
            - redis-stack
    redis-stack:
        image: "redis/redis-stack-server:latest"
        ports:
            - "6379:6379"
#     caddy:
#         image: caddy:2.6.2-alpine
#         container_name: caddy-service
#         restart: unless-stopped
#         ports:
#             - "80:80"
#             - "443:443"
#         volumes:
#             - $PWD/Caddyfile:/etc/caddy/Caddyfile
#             - $PWD/site:/srv
#             - caddy_data:/data
#             - caddy_config:/config

# volumes:
#     caddy_data:
#     caddy_config:
