name: Deploy to Digital Ocean CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
            - name: Reload backend execution
              run: pm2 reload themindgame
