name: Deploy CI

on:
    push:
        branches: ["push"]
    pull_request:
        branches: ["push"]

jobs:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
    - run: npm install
          npm run build
