name: Deploy to Digital Ocean CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
            - name: PM2 save
              run: pm2 save
            - name: PM2 list
              run: pm2 list
            # - name: PM2 install
            #   run: npm run pm2:install
            # - name: PM2 stop
            #   run: npm run pm2:stop
            # - name: PM2 save
            #   run: npm run pm2:save
            # - name: PM2 start
            #   run: npm run pm2:start
            - name: PM2 reload
              run: npx pm2 reload themindgame
            - name: PM2 save
              run: npm run pm2:save
